### ISSUE TITLE
Update instructions incorrect

### ISSUE THREAD

**Issue by luceos** [datlechin/flarum-simple-tour-guide#8]
Hi @datlechin,

In your readme and on discuss you mention for updating:

```
composer update datlechin/flarum-simple-tour-guide:"*"
```

The composer update command does not take a constraint though and this command will error when executed. If you want to guarantee people keep upgrading to the latest version, use the `require` command - identical to the install instructions you gave.

```
composer require datlechin/flarum-simple-tour-guide:"*"
```

🙏 keep up the good work!

Daniël.

**Comment by datlechin** [comment]
Hi thanks, I've updated the update instructions
